// <auto-generated />
using System;
using ExpertZonez.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExpertZonez.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260402091350_GenreTableAdded")]
    partial class GenreTableAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Assignment", b =>
                {
                    b.Property<int>("assignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("assignmentId"));

                    b.Property<string>("adminNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("assignedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("assignedByAdminId")
                        .HasColumnType("int");

                    b.Property<int>("requestId")
                        .HasColumnType("int");

                    b.Property<string>("status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Pending");

                    b.Property<int>("workerId")
                        .HasColumnType("int");

                    b.HasKey("assignmentId");

                    b.HasIndex("requestId");

                    b.HasIndex("workerId");

                    b.ToTable("Assignments");
                });

            modelBuilder.Entity("Customer", b =>
                {
                    b.Property<int>("custId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("custId"));

                    b.Property<DateTime>("custCreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("custEmail")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("custName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("custPasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("custPhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("custRole")
                        .HasMaxLength(20)
                        .HasColumnType("int");

                    b.HasKey("custId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("ExpertZonez.API.Models.ServiceGenre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("genreName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("ServiceGenres");
                });

            modelBuilder.Entity("Service", b =>
                {
                    b.Property<int>("serviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("serviceId"));

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<string>("serviceDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("serviceIcon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("serviceName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("serviceId");

                    b.HasIndex("GenreId");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("ServiceRequest", b =>
                {
                    b.Property<int>("serviceRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("serviceRequestId"));

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("custLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("custName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("custPhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("requestStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("serviceDateAndTIme")
                        .HasColumnType("datetime2");

                    b.Property<int>("serviceId")
                        .HasColumnType("int");

                    b.Property<int?>("userId")
                        .HasColumnType("int");

                    b.HasKey("serviceRequestId");

                    b.HasIndex("serviceId");

                    b.HasIndex("userId");

                    b.ToTable("ServiceRequests");
                });

            modelBuilder.Entity("Worker", b =>
                {
                    b.Property<int>("workerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("workerId"));

                    b.Property<bool>("didWorkerIsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("didWorkerIsApproved")
                        .HasColumnType("bit");

                    b.Property<bool>("didWorkerIsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("workerAddress")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("workerCNIC")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("workerCreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("workerExperienceYears")
                        .HasColumnType("int");

                    b.Property<string>("workerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("workerPhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("workerId");

                    b.ToTable("Workers");
                });

            modelBuilder.Entity("WorkerService", b =>
                {
                    b.Property<int>("workerId")
                        .HasColumnType("int");

                    b.Property<int>("serviceId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("workerId", "serviceId");

                    b.HasIndex("serviceId");

                    b.ToTable("WorkerServices");
                });

            modelBuilder.Entity("Assignment", b =>
                {
                    b.HasOne("ServiceRequest", "serviceRequest")
                        .WithMany()
                        .HasForeignKey("requestId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Worker", "worker")
                        .WithMany()
                        .HasForeignKey("workerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("serviceRequest");

                    b.Navigation("worker");
                });

            modelBuilder.Entity("Service", b =>
                {
                    b.HasOne("ExpertZonez.API.Models.ServiceGenre", "Genre")
                        .WithMany("services")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("ServiceRequest", b =>
                {
                    b.HasOne("Service", "service")
                        .WithMany()
                        .HasForeignKey("serviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Customer", "user")
                        .WithMany()
                        .HasForeignKey("userId");

                    b.Navigation("service");

                    b.Navigation("user");
                });

            modelBuilder.Entity("WorkerService", b =>
                {
                    b.HasOne("Service", "service")
                        .WithMany("workerServices")
                        .HasForeignKey("serviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Worker", "worker")
                        .WithMany("WorkerServices")
                        .HasForeignKey("workerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("service");

                    b.Navigation("worker");
                });

            modelBuilder.Entity("ExpertZonez.API.Models.ServiceGenre", b =>
                {
                    b.Navigation("services");
                });

            modelBuilder.Entity("Service", b =>
                {
                    b.Navigation("workerServices");
                });

            modelBuilder.Entity("Worker", b =>
                {
                    b.Navigation("WorkerServices");
                });
#pragma warning restore 612, 618
        }
    }
}
